name: taskhive
description: "A Smart Productivity Manager for students and young professionals"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.2
  sqflite_common_ffi_web: ^0.4.2+3
  path: ^1.8.3
  shared_preferences: ^2.2.2
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Maps
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  confetti: ^0.7.0
  
  # Audio/Video
  video_player: ^2.8.1
  audioplayers: ^5.2.1
  
  # UI/UX
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  
  # State Management
  provider: ^6.1.1
  
  # HTTP/API
  http: ^1.1.2
  
  # File handling
  path_provider: ^2.1.1
  
  # Charts
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/audio/
    - assets/audio/success.mp3
    - assets/images/
    - assets/themes/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
